apiVersion: skaffold/v2beta7
kind: Config
build:
  googleCloudBuild:
    projectId: testingproject-19c4c
  artifacts:
  - image: gcr.io/testingproject-19c4c/whereami
deploy:
  kubectl:
    manifests:
      - k8s/*
